name: DoxygenAutoDocSync
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    
    - name: Checkout code with submodules
      uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Extract Branch Name
      id: extract_branch_name
      run: |
        BRANCH_NAME_BUF=$(echo $GITHUB_REF | sed -e 's/.*\///')
        echo "BRANCH_NAME=$BRANCH_NAME_BUF" >> $GITHUB_ENV 
  
    - name: Prepare Variables
      run: |
        export OWNER=$(echo ${{ github.repository }} | cut -d'/' -f1)
        export REPO_NAME=$(echo ${{ github.repository }} | cut -d'/' -f2)
        echo "DOC_REPO=$OWNER/DOC-$REPO_NAME" >> $GITHUB_OUTPUT
        echo "BRANCH_NAME=${{ env.BRANCH_NAME }}" >> $GITHUB_OUTPUT
        
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: artifact
        path: ./
     
  call-reusable-workflow:
    needs: build
    uses: 701Enti/Github-WorkFlows/.github/workflows/doxygen-auto-code-to-doc.yml@master
    with:
      docRepo: ${{ needs.build.outputs.DOC_REPO }}
      BRANCH_NAME: ${{ needs.build.outputs.BRANCH_NAME }}
    secrets:
      docRepoSecret: ${{ secrets.DOC_REPO_SYNC_SECRET }}
      
        
